# continue_training:
data:
  trainset: /Users/easton/Projects/OpenASR_BaiYe/egs/callhome_hkust/data/train/
  devset: /Users/easton/Projects/OpenASR_BaiYe/egs/callhome_hkust/data/dev/ja.json
  vocab_path: /Users/easton/Projects/OpenASR_BaiYe/egs/callhome_hkust/data/callhome.IPA
  maxlen: 200
  fetchworker_num: 1
model:
  type: CIF
  add_eos: False
  add_blk: True
  signal:
    feature_type: offline
    spec_aug:
        freq_mask_num: 2
        freq_mask_width: 27
        time_mask_num: 2
        time_mask_width: 40
  encoder:
    type: Transformer
    sub:
      type: ConvV2
      layer_num: 1
    input_dim: 80
    d_model: 512
    nhead: 2
    dim_feedforward: 2048
    activation: "glu"
    num_layers: 1
    dropout_rate: 0.1
  assigner:
    d_model: 512
    n_layers: 3
    w_context: 3
    dropout: 0.1
  decoder:
    type: FC
    vocab_size: -1 # derived by tokenizer
    encoder_dim: 512
training:
    label_type: phones
    batch_frames: 1000
    multi_gpu: False
    exp_dir: exp/cif
    print_inteval: 10
    num_epoch: 80
    accumulate_grad_batch: 2
    init_lr: 1.0
    optimtype: adam
    grad_max_norm: 50.
    label_smooth: 0.1
    lambda_qua: 0.1
    lambda_ctc: 1.0
    num_last_ckpt_keep: 1
    lr_scheduler:
        type: "warmup_transformer"
        warmup_step: 10000
        d_model: 512
