continue_training:
data:
  trainset: /home/easton/projects/OpenASR_BaiYe/egs/aishell1/s5/data/train.json
  devset: /home/easton/projects/OpenASR_BaiYe/egs/aishell1/s5/data/dev.json
  vocab_path: /home/easton/projects/OpenASR_BaiYe/egs/aishell1/s5/data/aishell1_train_chars.txt
  maxlen: 60
  fetchworker_num: 12
model:
  type: CIF
  no_eos: True
  signal:
    feature_type: fbank
    sample_rate: 16000
    num_mel_bins: 80
    use_energy: False
    spec_aug:
        freq_mask_num: 2
        freq_mask_width: 27
        time_mask_num: 2
        time_mask_width: 40
  encoder:
    type: Transformer
    sub:
      type: ConvV2
      layer_num: 2
    input_dim: 80
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    activation: "glu"
    num_layers: 6
    dropout_rate: 0.1
  assigner:
    d_model: 512
    n_layers: 1
    w_context: 3
    dropout: 0.1
  decoder:
    type: TransformerDecoder
    vocab_size: -1 # derived by tokenizer
    d_model: 512
    nhead: 8
    num_layers: 6
    encoder_dim: 512
    dim_feedforward: 2048
    activation: "glu"
    dropout_rate: 0.1
training:
    batch_time: 150
    multi_gpu: False
    exp_dir: exp/cif_2
    print_inteval: 10
    num_epoch: 80
    accumulate_grad_batch: 8
    init_lr: 1.0
    optimtype: adam
    grad_max_norm: 50.
    label_smooth: 0.1
    lambda_qua: 0.01
    lr_scheduler:
        type: "warmup_transformer"
        warmup_step: 16000
        d_model: 512
